/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as StoreRouteImport } from './routes/_store'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as StoreIndexRouteImport } from './routes/_store.index'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminInventoryRouteImport } from './routes/admin.inventory'
import { Route as StoreCheckoutRouteImport } from './routes/_store.checkout'
import { Route as StoreCatalogRouteImport } from './routes/_store.catalog'
import { Route as StoreCartRouteImport } from './routes/_store.cart'
import { Route as StoreAccountRouteImport } from './routes/_store.account'
import { Route as StoreProductSlugRouteImport } from './routes/_store.product.$slug'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/_store',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const StoreIndexRoute = StoreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoreRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const StoreCheckoutRoute = StoreCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => StoreRoute,
} as any)
const StoreCatalogRoute = StoreCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => StoreRoute,
} as any)
const StoreCartRoute = StoreCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => StoreRoute,
} as any)
const StoreAccountRoute = StoreAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => StoreRoute,
} as any)
const StoreProductSlugRoute = StoreProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => StoreRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof StoreIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/account': typeof StoreAccountRoute
  '/cart': typeof StoreCartRoute
  '/catalog': typeof StoreCatalogRoute
  '/checkout': typeof StoreCheckoutRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/': typeof AdminIndexRoute
  '/product/$slug': typeof StoreProductSlugRoute
}
export interface FileRoutesByTo {
  '/account': typeof StoreAccountRoute
  '/cart': typeof StoreCartRoute
  '/catalog': typeof StoreCatalogRoute
  '/checkout': typeof StoreCheckoutRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/': typeof StoreIndexRoute
  '/admin': typeof AdminIndexRoute
  '/product/$slug': typeof StoreProductSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_store': typeof StoreRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/_store/account': typeof StoreAccountRoute
  '/_store/cart': typeof StoreCartRoute
  '/_store/catalog': typeof StoreCatalogRoute
  '/_store/checkout': typeof StoreCheckoutRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/_store/': typeof StoreIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_store/product/$slug': typeof StoreProductSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/account'
    | '/cart'
    | '/catalog'
    | '/checkout'
    | '/admin/inventory'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/'
    | '/product/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/account'
    | '/cart'
    | '/catalog'
    | '/checkout'
    | '/admin/inventory'
    | '/admin/orders'
    | '/admin/payments'
    | '/'
    | '/admin'
    | '/product/$slug'
  id:
    | '__root__'
    | '/_store'
    | '/admin'
    | '/_store/account'
    | '/_store/cart'
    | '/_store/catalog'
    | '/_store/checkout'
    | '/admin/inventory'
    | '/admin/orders'
    | '/admin/payments'
    | '/_store/'
    | '/admin/'
    | '/_store/product/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  StoreRoute: typeof StoreRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_store': {
      id: '/_store'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_store/': {
      id: '/_store/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof StoreIndexRouteImport
      parentRoute: typeof StoreRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_store/checkout': {
      id: '/_store/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof StoreCheckoutRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/catalog': {
      id: '/_store/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof StoreCatalogRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/cart': {
      id: '/_store/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof StoreCartRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/account': {
      id: '/_store/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof StoreAccountRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/product/$slug': {
      id: '/_store/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof StoreProductSlugRouteImport
      parentRoute: typeof StoreRoute
    }
  }
}

interface StoreRouteChildren {
  StoreAccountRoute: typeof StoreAccountRoute
  StoreCartRoute: typeof StoreCartRoute
  StoreCatalogRoute: typeof StoreCatalogRoute
  StoreCheckoutRoute: typeof StoreCheckoutRoute
  StoreIndexRoute: typeof StoreIndexRoute
  StoreProductSlugRoute: typeof StoreProductSlugRoute
}

const StoreRouteChildren: StoreRouteChildren = {
  StoreAccountRoute: StoreAccountRoute,
  StoreCartRoute: StoreCartRoute,
  StoreCatalogRoute: StoreCatalogRoute,
  StoreCheckoutRoute: StoreCheckoutRoute,
  StoreIndexRoute: StoreIndexRoute,
  StoreProductSlugRoute: StoreProductSlugRoute,
}

const StoreRouteWithChildren = StoreRoute._addFileChildren(StoreRouteChildren)

interface AdminRouteChildren {
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminInventoryRoute: AdminInventoryRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  StoreRoute: StoreRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
